server.port=2007
spring.datasource.url=jdbc:mysql://localhost:3309/accountsdb_qa
spring.profiles.active=${ACTIVE_PROFILE}

accounts:
  accountNumber: 98765
  accountType: Savings Account - QA
  branchAddress: Santosh Nagar, Hyderabad