server:
  port: 2027
spring:
  profiles:
    activate:
      on-profile: prod
  datasource:
    username: sa
    password:
    url: jdbc:mysql://localhost:3306/accountservices_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: update
accounts:
  accounts-account-number: "98765"
  accounts-account-type: "Savings Account - PRODUCTION"
  accounts-branch-address: "NallurHalli, Bangalore"