server:
  port: 2027
spring:
  profiles:
    activate:
      on-profile: prod
  datasource:
    username: sa
    password:
    url: jdbc:mysql://localhost:3306/accountservices_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: update

build:
  artifact: account-service-prod
  version: 1.0.0

accounts:
  account-number: "98765"
  account-type: "Savings Account - PRODUCTION"
  branch-address: "NallurHalli, Bangalore"