server.port=2027
spring.datasource.url=jdbc:mysql://localhost:3310/accountsdb_prod
spring.profiles.activate.on-profile=prod

build:
  artifact: account-service-prod
  version: 1.0.0

accounts:
  account-number: 98765
  account-type: Savings Account - PRODUCTION
  branch-address: NallurHalli, Bangalore