server.port=2028
spring.application.name=loan-service
spring.profiles.active=${ACTIVE_PROFILE}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3311/loanservices_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true