spring.application.name=loan-service
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password="{cipher}85b7f801f6fc279bd415fec07456caeb34c7f316cf7cbbad9cc24cfd9454ca4e"
spring.datasource.url=jdbc:mysql://localhost:3312/loanservices_prod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.config.activate.on-profile=prod

#LOANS
loans.loan-account-number= 12345
loans.loan-type= Home Loan - PRODUCTION
loans.loan-amount= 100000
loans.tenure-in-months= 120
loans.interest-rate= 6.5